name: invoiso
description: "Invoice generating desktop app built with Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.11.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.6
  path: ^1.8.3
  path_provider: ^2.0.15
  file_picker: ^10.2.0
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  crypto: ^3.0.3
  uuid: ^4.0.0
  csv: ^6.0.0
  archive: ^4.0.0
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.8.4
  open_file: ^3.3.2
  url_launcher: ^6.2.6
  http: ^1.2.0
  fl_chart: ^0.69.0
  downloads_path_provider_28: any
  syncfusion_flutter_pdfviewer: ^30.1.40
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0
  flutter_svg: ^2.0.10+1
  image: ^4.2.0
  qr: ^3.0.1
  flex_color_picker: ^3.6.0
  thermal_printer: ^1.0.5
  flutter_esc_pos_utils: ^1.0.1
  file_saver: ^0.4.0
  google_fonts: ^8.2.1
  sqflite_common_ffi_web: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  package_rename: ^1.10.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/logo.png
   - assets/images/yatri_logo.png
   - assets/images/yatricloud_logo.png
   - assets/images/logo_dark.png
   - assets/images/logo.svg
   - assets/images/logo_v.png
   - assets/images/logo_v_dark.png
   - assets/templates/classic.png
   - assets/templates/modern.png
   - assets/templates/minimal.png
   - assets/fonts/DejaVuSans.ttf
   - assets/fonts/DejaVuSans-Bold.ttf
   - assets/fonts/DejaVuSans-Oblique.ttf
   - assets/fonts/DejaVuSans-BoldOblique.ttf
   - assets/fonts/lklug.ttf
   - assets/fonts/NotoSansDevanagari-Bold.ttf
   - assets/fonts/NotoSansDevanagari-Regular.ttf
   - assets/fonts/NotoSansMalayalam-Bold.ttf
   - assets/fonts/NotoSansMalayalam-Regular.ttf
   - assets/fonts/NotoSansTamil-Regular.ttf
   - assets/fonts/NotoSansTamil-Bold.ttf
   - assets/fonts/NotoSansKannada-Regular.ttf
   - assets/fonts/NotoSansKannada-Bold.ttf
   - assets/fonts/NotoSansTelugu-Regular.ttf
   - assets/fonts/NotoSansTelugu-Bold.ttf

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/images/logo_v.png"

package_rename_config:
  linux:
    app_name: Yatri Billing
    package_name: yatri_billing
    exe_name: yatri_billing

  windows:
    app_name: Yatri Billing
    organization: Yatri Cloud
    copyright_notice: Copyright ©️ 2026 Yatri Cloud. All rights reserved.
    exe_name: yatri_billing

  web:
    app_name: Yatri Billing
    short_app_name: Yatri Billing
    description: Cloud-Native & Offline Invoicing Platform by Yatri Cloud
