enum InvoiceTemplate {
  classic,
  modern,
  minimal,
  executive,
  compact, // A6-optimized compact/receipt template
  thermal, // 80mm/58mm thermal receipt template
  gridClassic, // Bordered grid "old style" bill, adaptive A4/A5/A6
}

class ProductUnits {
  static const List<String> presets = [
    'pcs', 'kg', 'gm', 'ltr', 'ml', 'mtr', 'cm', 'box', 'bag',
    'dozen', 'set', 'pair', 'roll', 'sqft', 'unit',
  ];
}

enum BackupType { database, json }

enum SettingKey {
  logoPosition,
  invoicePrefix,
  additionalInfo,
  thankYouNote,
  currency,
  upiId, // kept for backward-compat read only
  showUpiQr,
  upiIds, // JSON list of UpiEntry objects
  showGstFields, // whether to show GST/GSTIN fields
  fractionalQuantity, // whether to allow decimal quantities (e.g. 1.5 hrs)
  quantityLabel, // default label for the Qty column (e.g. "Words", "Hours")
  logoSize, // logo size on PDF: 'xsmall' | 'small' | 'medium' | 'large'
  businessType, // 'product' | 'service' | 'both'
  showQuantity, // whether to show quantity field (default true)
  bankAccounts, // JSON list of BankAccount objects
  showBankDetails, // whether to show bank details on PDF
  showDiscount, // whether to show discount column on PDF (default true)
  showTypeTag, // whether to show product/service tag on invoice items (default true)
  lastUpdateCheck, // ISO timestamp of last GitHub release API call
  lastKnownLatestVersion, // latest version tag returned by last API call
  lastNotifiedVersion, // version for which the update dialog was last shown
  dateFormat, // date display pattern: 'dd/MM/yyyy' | 'MM/dd/yyyy' | 'dd MMM yyyy' | 'yyyy-MM-dd'
  showInvoiceFooterBranding, // show "Generated by Yatri Billing" in invoice PDF footer
  pdfThemeColor, // custom PDF accent/theme color as #RRGGBB
  dashboardLayout, // which dashboard layout to use: 'default' | 'classic' | 'simple'
  layoutBannerDismissed, // '1' once user dismisses the new-layouts discovery banner
  themeBannerDismissed, // '1' once user dismisses the dark-mode (beta) discovery banner
  signatureImage, // base64-encoded signature image
  signaturePosition, // 'left' | 'right'
  signatureSize, // signature size on PDF: 'small' | 'medium' | 'large'
  showPreviousBalance, // whether to show calculated Previous Balance Due on PDFs
  pageSize, // 'a4' | 'a6'
  showTotalQuantity, // show total quantity row in compact template footer
  supportBannerDismissed, // milestone at which support banner was last dismissed: '10' | '50' | '100'
  invoiceStartingNumber, // starting invoice number (only editable when invoice count is zero)
  defaultTaxRate, // default invoice tax rate percentage (e.g. '18')
  thermalWidthMargin, // chars trimmed off the thermal printer's textbook width to avoid edge clipping on real hardware; default '1'
  thermalItemLayout, // 'table' | 'detailed' — how items print on thermal receipts; default 'table'
  invoiceTemplate, // used by cloud edition's generic setSetting/getSetting path
  companyLogo, // used by cloud edition's generic setSetting/getSetting path
  installationId, // Unique identifier for this installation. Generated on first launch and persisted locally. Used for anonymous analytics and installation tracking.
  showAliasNameInPdf, // whether to print a product's local-language alias name instead of its actual name on PDFs (default false)
  showTaxButtonInInvoicePage,
  themeMode, // app theme: 'light' | 'dark' | 'system'
  watermarkImage, // base64-encoded watermark image shown behind invoice items table
  watermarkOpacity, // watermark opacity 0.0-1.0 as string; default '0.12'
  defaultInvoiceTitle, // GST document title preselected on new invoices: 'Tax Invoice' | 'Bill of Supply' | etc; null/empty = plain 'Invoice'
  allowDuplicateInvoiceItems, // whether the same product can be added twice to one invoice (default false)
  showCgstSgst, // whether to split tax into CGST/SGST (India, 50/50)
  defaultTaxMode, // 'global' | 'perItem' — default tax mode for new invoices
  showRoundOff, // whether to show round-off row + amount-in-words on PDFs (default false)
}

extension SettingKeyExtension on SettingKey {
  String get key {
    switch (this) {
      case SettingKey.logoPosition:
        return 'logo_position';
      case SettingKey.invoicePrefix:
        return 'invoice_prefix';
      case SettingKey.additionalInfo:
        return 'additional_info';
      case SettingKey.thankYouNote:
        return 'thank_you_note';
      case SettingKey.currency:
        return 'currency';
      case SettingKey.upiId:
        return 'upi_id';
      case SettingKey.showUpiQr:
        return 'show_upi_qr';
      case SettingKey.upiIds:
        return 'upi_ids';
      case SettingKey.showGstFields:
        return 'show_gst_fields';
      case SettingKey.fractionalQuantity:
        return 'fractional_quantity';
      case SettingKey.quantityLabel:
        return 'quantity_label';
      case SettingKey.logoSize:
        return 'logo_size';
      case SettingKey.businessType:
        return 'business_type';
      case SettingKey.showQuantity:
        return 'show_quantity';
      case SettingKey.bankAccounts:
        return 'bank_accounts';
      case SettingKey.showBankDetails:
        return 'show_bank_details';
      case SettingKey.showDiscount:
        return 'show_discount';
      case SettingKey.showTypeTag:
        return 'show_type_tag';
      case SettingKey.lastUpdateCheck:
        return 'last_update_check';
      case SettingKey.lastKnownLatestVersion:
        return 'last_known_latest_version';
      case SettingKey.lastNotifiedVersion:
        return 'last_notified_version';
      case SettingKey.dateFormat:
        return 'date_format';
      case SettingKey.showInvoiceFooterBranding:
        return 'show_invoice_footer_branding';
      case SettingKey.pdfThemeColor:
        return 'pdf_theme_color';
      case SettingKey.dashboardLayout:
        return 'dashboard_layout';
      case SettingKey.layoutBannerDismissed:
        return 'layout_banner_dismissed';
      case SettingKey.themeBannerDismissed:
        return 'theme_banner_dismissed';
      case SettingKey.signatureImage:
        return 'signature_image';
      case SettingKey.signaturePosition:
        return 'signature_position';
      case SettingKey.signatureSize:
        return 'signature_size';
      case SettingKey.showPreviousBalance:
        return 'show_previous_balance';
      case SettingKey.pageSize:
        return 'page_size';
      case SettingKey.showTotalQuantity:
        return 'show_total_quantity';
      case SettingKey.supportBannerDismissed:
        return 'support_banner_dismissed';
      case SettingKey.invoiceStartingNumber:
        return 'invoice_starting_number';
      case SettingKey.defaultTaxRate:
        return 'default_tax_rate';
      case SettingKey.thermalWidthMargin:
        return 'thermal_width_margin';
      case SettingKey.thermalItemLayout:
        return 'thermal_item_layout';
      case SettingKey.invoiceTemplate:
        return 'invoice_template';
      case SettingKey.companyLogo:
        return 'company_logo';
      case SettingKey.installationId:
        return 'installation_id';
      case SettingKey.showAliasNameInPdf:
        return 'show_alias_name_in_pdf';
      case SettingKey.showTaxButtonInInvoicePage:
        return 'show_tax_button_in_invoice_page';
      case SettingKey.themeMode:
        return 'theme_mode';
      case SettingKey.watermarkImage:
        return 'watermark_image';
      case SettingKey.watermarkOpacity:
        return 'watermark_opacity';
      case SettingKey.defaultInvoiceTitle:
        return 'default_invoice_title';
      case SettingKey.allowDuplicateInvoiceItems:
        return 'allow_duplicate_invoice_items';
      case SettingKey.showCgstSgst:
        return 'show_cgst_sgst';
      case SettingKey.defaultTaxMode:
        return 'default_tax_mode';
      case SettingKey.showRoundOff:
        return 'show_round_off';
    }
  }
}

enum PageSize { a4, a5, a6, thermal80, thermal58 }

extension InvoiceTemplatePageSizeExtension on InvoiceTemplate {
  bool supportsPageSize(PageSize pageSize) {
    switch (pageSize) {
      case PageSize.a6:
        return this == InvoiceTemplate.compact ||
            this == InvoiceTemplate.gridClassic;
      case PageSize.a5:
        return this == InvoiceTemplate.gridClassic;
      case PageSize.thermal80:
      case PageSize.thermal58:
        return this == InvoiceTemplate.thermal;
      case PageSize.a4:
        return this != InvoiceTemplate.compact &&
            this != InvoiceTemplate.thermal;
    }
  }
}

InvoiceTemplate defaultInvoiceTemplateForPageSize(PageSize pageSize) {
  switch (pageSize) {
    case PageSize.a6:
      return InvoiceTemplate.compact;
    case PageSize.a5:
      return InvoiceTemplate.gridClassic;
    case PageSize.thermal80:
    case PageSize.thermal58:
      return InvoiceTemplate.thermal;
    default:
      return InvoiceTemplate.classic;
  }
}

InvoiceTemplate effectiveInvoiceTemplateForPageSize(
  InvoiceTemplate template,
  PageSize pageSize,
) {
  return template.supportsPageSize(pageSize)
      ? template
      : defaultInvoiceTemplateForPageSize(pageSize);
}

extension PageSizeExtension on PageSize {
  String get key {
    switch (this) {
      case PageSize.a4:
        return 'a4';
      case PageSize.a5:
        return 'a5';
      case PageSize.a6:
        return 'a6';
      case PageSize.thermal80:
        return 'thermal80';
      case PageSize.thermal58:
        return 'thermal58';
    }
  }

  String get label {
    switch (this) {
      case PageSize.a4:
        return 'Standard A4';
      case PageSize.a5:
        return 'Standard A5';
      case PageSize.a6:
        return 'Standard A6';
      case PageSize.thermal80:
        return 'Thermal Paper 80mm';
      case PageSize.thermal58:
        return 'Thermal Paper 58mm';
    }
  }

  static PageSize fromKey(String? key) {
    switch (key) {
      case 'a5':
        return PageSize.a5;
      case 'a6':
        return PageSize.a6;
      case 'thermal80':
        return PageSize.thermal80;
      case 'thermal58':
        return PageSize.thermal58;
      default:
        return PageSize.a4;
    }
  }
}

class CompactPdfTotalsStyle {
  const CompactPdfTotalsStyle({
    this.width = 128,
    this.rowFontSize = 5.5,
    this.highlightFontSize = 6.0,
    this.rowHorizontalPadding = 4,
    this.rowVerticalPadding = 2,
    this.highlightHorizontalPadding = 4,
    this.highlightVerticalPadding = 3,
    this.borderRadius = 4,
  });

  final double width;
  final double rowFontSize;
  final double highlightFontSize;
  final double rowHorizontalPadding;
  final double rowVerticalPadding;
  final double highlightHorizontalPadding;
  final double highlightVerticalPadding;
  final double borderRadius;
}

const compactPdfTotalsStyle = CompactPdfTotalsStyle();

class CompactPdfLayoutStyle {
  const CompactPdfLayoutStyle({
    this.logoScale = 0.6,
    this.tableFontSize = 6.4,
    this.tableHorizontalPadding = 4,
    this.tableVerticalPadding = 2.2,
    this.headerGap = 5,
    this.headerPadding = 4,
    this.signatureTopGap = 5,
    this.signatureImageHeight = 24,
    this.signatureLabelGap = 1.5,
    this.signatureLabelFontSize = 5.8,
    this.footerBrandingFontSize = 5.6,
    this.footerTopMargin = 4,
    this.titleFontSize = 13,
    this.subtitleFontSize = 8,
    this.bodyFontSize = 9,
    this.totalsFontSize = 10,
  });

  final double logoScale;
  final double tableFontSize;
  final double tableHorizontalPadding;
  final double tableVerticalPadding;
  final double headerGap;
  final double headerPadding;
  final double signatureTopGap;
  final double signatureImageHeight;
  final double signatureLabelGap;
  final double signatureLabelFontSize;
  final double footerBrandingFontSize;
  final double footerTopMargin;
  final double titleFontSize;
  final double subtitleFontSize;
  final double bodyFontSize;
  final double totalsFontSize;
}

const compactPdfLayoutStyle = CompactPdfLayoutStyle();

/// Tunable font sizes/paddings for a single PDF template. One const instance
/// per template (below) holds that template's current values as defaults —
/// edit an instance's values here to restyle that template everywhere.
class PdfTemplateStyle {
  const PdfTemplateStyle({
    this.titleFontSize = 14,
    this.subtitleFontSize = 9,
    this.labelFontSize = 8,
    this.bodyFontSize = 9,
    this.tableHeaderFontSize = 8,
    this.tableFontSize = 8,
    this.totalsFontSize = 9,
    this.totalsHighlightFontSize = 11,
    this.footerFontSize = 8,
    this.cellPaddingH = 6,
    this.cellPaddingV = 6,
    this.sectionPadding = 8,
    this.headerGap = 6,
    this.typeFont = 10,
  });

  final double titleFontSize;
  final double subtitleFontSize;
  final double labelFontSize;
  final double bodyFontSize;
  final double tableHeaderFontSize;
  final double tableFontSize;
  final double totalsFontSize;
  final double totalsHighlightFontSize;
  final double footerFontSize;
  final double cellPaddingH;
  final double cellPaddingV;
  final double sectionPadding;
  final double headerGap;
  final double typeFont;
}

const classicPdfStyle = PdfTemplateStyle(
  titleFontSize: 14,
  subtitleFontSize: 8,
  labelFontSize: 8,
  bodyFontSize: 8,
  headerGap: 2,
  sectionPadding: 4,
  tableFontSize: 8,
  typeFont: 10,
);
const executivePdfStyle = PdfTemplateStyle(
  titleFontSize: 14,
  subtitleFontSize: 9,
  labelFontSize: 8,
  bodyFontSize: 8,
  sectionPadding: 8,
  headerGap: 6,
);
const minimalPdfStyle = PdfTemplateStyle(
  titleFontSize: 12,
  subtitleFontSize: 9,
  labelFontSize: 9,
  bodyFontSize: 8,
  headerGap: 5,
);
const modernPdfStyle = PdfTemplateStyle(
  titleFontSize: 15,
  subtitleFontSize: 10,
  labelFontSize: 10,
  bodyFontSize: 8,
  sectionPadding: 10,
  headerGap: 8,
  tableFontSize: 8,
  typeFont: 10
);
const gridClassicPdfStyle = PdfTemplateStyle(
  titleFontSize: 12,
  subtitleFontSize: 8,
  labelFontSize: 7.5,
  bodyFontSize: 9,
  tableHeaderFontSize: 7.5,
  tableFontSize: 7.5,
  totalsFontSize: 8,
  totalsHighlightFontSize: 10,
  footerFontSize: 7,
  cellPaddingH: 4,
  cellPaddingV: 4,
  sectionPadding: 7,
  headerGap: 6,
);

enum DateFormatOption {
  ddmmyyyy, // dd/MM/yyyy  — default
  mmddyyyy, // MM/dd/yyyy  — US
  ddMmmyyyy, // dd MMM yyyy — unambiguous
  yyyymmdd, // yyyy-MM-dd  — ISO
}

extension DateFormatOptionExtension on DateFormatOption {
  String get key {
    switch (this) {
      case DateFormatOption.ddmmyyyy:
        return 'dd/MM/yyyy';
      case DateFormatOption.mmddyyyy:
        return 'MM/dd/yyyy';
      case DateFormatOption.ddMmmyyyy:
        return 'dd MMM yyyy';
      case DateFormatOption.yyyymmdd:
        return 'yyyy-MM-dd';
    }
  }

  String get label {
    switch (this) {
      case DateFormatOption.ddmmyyyy:
        return 'DD/MM/YYYY  (e.g. 15/04/2026)';
      case DateFormatOption.mmddyyyy:
        return 'MM/DD/YYYY  (e.g. 04/15/2026)';
      case DateFormatOption.ddMmmyyyy:
        return 'DD MMM YYYY  (e.g. 15 Apr 2026)';
      case DateFormatOption.yyyymmdd:
        return 'YYYY-MM-DD  (e.g. 2026-04-15)';
    }
  }

  static DateFormatOption fromKey(String? key) {
    switch (key) {
      case 'MM/dd/yyyy':
        return DateFormatOption.mmddyyyy;
      case 'dd MMM yyyy':
        return DateFormatOption.ddMmmyyyy;
      case 'yyyy-MM-dd':
        return DateFormatOption.yyyymmdd;
      default:
        return DateFormatOption.ddmmyyyy;
    }
  }
}

enum BusinessType {
  product,
  service,
  both,
}

extension BusinessTypeExtension on BusinessType {
  String get key {
    switch (this) {
      case BusinessType.product:
        return 'product';
      case BusinessType.service:
        return 'service';
      case BusinessType.both:
        return 'both';
    }
  }

  String get label {
    switch (this) {
      case BusinessType.product:
        return 'Product-based';
      case BusinessType.service:
        return 'Service-based';
      case BusinessType.both:
        return 'Both';
    }
  }

  static BusinessType fromKey(String? key) {
    switch (key) {
      case 'product':
        return BusinessType.product;
      case 'service':
        return BusinessType.service;
      default:
        return BusinessType.both;
    }
  }
}

/// A single UPI payment account entry.
class UpiEntry {
  final String label; // friendly name, e.g. "HDFC Bank" (may be empty)
  final String id; // UPI ID, e.g. "business@okhdfcbank"
  final bool isDefault; // whether this is the default account

  const UpiEntry(
      {required this.label, required this.id, this.isDefault = false});

  Map<String, dynamic> toJson() =>
      {'label': label, 'id': id, 'isDefault': isDefault};

  factory UpiEntry.fromJson(Map<String, dynamic> json) => UpiEntry(
        label: json['label'] as String? ?? '',
        id: json['id'] as String? ?? '',
        isDefault: json['isDefault'] as bool? ?? false,
      );

  /// Returns the label if set, otherwise falls back to the UPI ID itself.
  String get displayLabel => label.trim().isNotEmpty ? label.trim() : id;
}

/// A single bank account entry.
class BankAccount {
  final String label; // friendly name, e.g. "Business Account"
  final String bankName; // e.g. "HDFC Bank"
  final String accountNumber; // e.g. "123456789012"
  final String ifscCode; // e.g. "HDFC0001234"
  final bool isDefault;

  const BankAccount({
    required this.label,
    required this.bankName,
    required this.accountNumber,
    required this.ifscCode,
    this.isDefault = false,
  });

  Map<String, dynamic> toJson() => {
        'label': label,
        'bankName': bankName,
        'accountNumber': accountNumber,
        'ifscCode': ifscCode,
        'isDefault': isDefault,
      };

  factory BankAccount.fromJson(Map<String, dynamic> json) => BankAccount(
        label: json['label'] as String? ?? '',
        bankName: json['bankName'] as String? ?? '',
        accountNumber: json['accountNumber'] as String? ?? '',
        ifscCode: json['ifscCode'] as String? ?? '',
        isDefault: json['isDefault'] as bool? ?? false,
      );

  String get displayLabel =>
      label.trim().isNotEmpty ? label.trim() : bankName.trim();
}

class CurrencyOption {
  final String code;
  final String symbol;
  final String name;

  const CurrencyOption({
    required this.code,
    required this.symbol,
    required this.name,
  });
}

class SupportedCurrencies {
  static const List<CurrencyOption> all = [
    // default currency
    CurrencyOption(code: 'INR', symbol: 'Rs.', name: 'Indian Rupee'),
    // sorted
    CurrencyOption(code: 'AED', symbol: 'AED.', name: 'UAE Dirham'),
    CurrencyOption(code: 'AUD', symbol: 'A\$', name: 'Australian Dollar'),
    CurrencyOption(code: 'CAD', symbol: 'C\$', name: 'Canadian Dollar'),
    CurrencyOption(code: 'EUR', symbol: '€', name: 'Euro'),
    CurrencyOption(code: 'GBP', symbol: '£', name: 'British Pound'),
    CurrencyOption(code: 'JMD', symbol: 'J\$', name: 'Jamaican Dollar'),
    CurrencyOption(code: 'JPY', symbol: '¥', name: 'Japanese Yen'),
    CurrencyOption(code: 'KES', symbol: 'KSh.', name: 'Kenyan Shilling'),
    CurrencyOption(code: 'LKR', symbol: 'රු', name: 'Sri Lankan Rupee'),
    CurrencyOption(code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha'),
    CurrencyOption(code: 'MYR', symbol: 'RM.', name: 'Malaysian Ringgit'),
    CurrencyOption(code: 'NGN', symbol: '₦', name: 'Nigerian Naira'),
    CurrencyOption(code: 'NPR', symbol: 'Rs.', name: 'Nepalese Rupee'),
    CurrencyOption(code: 'NZD', symbol: 'NZ\$', name: 'New Zealand Dollar'),
    CurrencyOption(code: 'OMR', symbol: 'OMR.', name: 'Omani Rial'),
    CurrencyOption(code: 'PKR', symbol: 'Rs.', name: 'Pakistani Rupee'),
    CurrencyOption(code: 'QAR', symbol: 'QAR.', name: 'Qatari Riyal'),
    CurrencyOption(code: 'SAR', symbol: 'SAR.', name: 'Saudi Riyal'),
    CurrencyOption(code: 'SGD', symbol: 'S\$', name: 'Singapore Dollar'),
    CurrencyOption(code: 'USD', symbol: '\$', name: 'US Dollar'),
    CurrencyOption(code: 'ZAR', symbol: 'R.', name: 'South African Rand'),
  ];

  static CurrencyOption fromCode(String code) {
    return all.firstWhere(
      (c) => c.code == code,
      orElse: () => all.first,
    );
  }
}

enum TaxMode {
  none,
  global,
  perItem,
}

extension TaxModeExtension on TaxMode {
  String get key {
    switch (this) {
      case TaxMode.none:
        return 'none';
      case TaxMode.global:
        return 'global';
      case TaxMode.perItem:
        return 'per_item';
    }
  }

  static TaxMode fromKey(String? key) {
    switch (key) {
      case 'none':
        return TaxMode.none;
      case 'per_item':
        return TaxMode.perItem;
      default:
        return TaxMode.global;
    }
  }
}

enum LogoPosition { left, right }

/// Returns the label used for a company's tax registration number on PDFs.
/// Falls back to 'GSTIN' for India and for unset countries (backward compat).
String taxLabel(String? country) {
  if (country == null || country.isEmpty || country == 'India') return 'GSTIN';
  return 'Tax/VAT No';
}

/// Returns the label for a personal tax ID field.
/// India → 'PAN', everyone else → 'TIN'.
String panLabel(String? country) {
  if (country == null || country.isEmpty || country == 'India') return 'PAN';
  return 'TIN';
}

/// True if country is unset (backward-compat) or explicitly India.
bool isIndiaCountry(String? country) =>
    country == null || country.isEmpty || country.toLowerCase() == 'india';

/// Full list of world countries (alphabetical).
class AppCountries {
  static const List<String> all = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Brazzaville)',
    'Congo (Kinshasa)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ];
}

enum PaymentStatus {
  unpaid,
  partial,
  paid,
}

extension LogoPositionExtension on LogoPosition {
  String get key {
    switch (this) {
      case LogoPosition.left:
        return 'left';
      case LogoPosition.right:
        return 'right';
    }
  }
}

enum LogoSize { xsmall, small, medium, large }

extension LogoSizeExtension on LogoSize {
  String get key {
    switch (this) {
      case LogoSize.xsmall:
        return 'xsmall';
      case LogoSize.small:
        return 'small';
      case LogoSize.medium:
        return 'medium';
      case LogoSize.large:
        return 'large';
    }
  }

  String get label {
    switch (this) {
      case LogoSize.xsmall:
        return 'X-Small';
      case LogoSize.small:
        return 'Small';
      case LogoSize.medium:
        return 'Medium';
      case LogoSize.large:
        return 'Large';
    }
  }

  /// Logo pixel size used when rendering the company logo on PDFs.
  double get pixelSize {
    switch (this) {
      case LogoSize.xsmall:
        return 40;
      case LogoSize.small:
        return 60;
      case LogoSize.medium:
        return 90;
      case LogoSize.large:
        return 120;
    }
  }
}

LogoSize logoSizeFromKey(String? key) {
  return LogoSize.values.firstWhere(
    (s) => s.key == key,
    orElse: () => LogoSize.medium,
  );
}

enum SignatureSize { small, medium, large }

extension SignatureSizeExtension on SignatureSize {
  String get key {
    switch (this) {
      case SignatureSize.small:
        return 'small';
      case SignatureSize.medium:
        return 'medium';
      case SignatureSize.large:
        return 'large';
    }
  }

  String get label {
    switch (this) {
      case SignatureSize.small:
        return 'Small';
      case SignatureSize.medium:
        return 'Medium';
      case SignatureSize.large:
        return 'Large';
    }
  }

  /// Signature image height (px) at the current default template scale (50 = medium).
  double get pixelHeight {
    switch (this) {
      case SignatureSize.small:
        return 35;
      case SignatureSize.medium:
        return 50;
      case SignatureSize.large:
        return 70;
    }
  }
}

SignatureSize signatureSizeFromKey(String? key) {
  return SignatureSize.values.firstWhere(
    (s) => s.key == key,
    orElse: () => SignatureSize.medium,
  );
}

/// Cleans and formats invoice numbers for display:
/// - Strips leading '#' symbol
/// - Strips excessive leading zeros (e.g. '00000001' becomes '001')
/// - Preserves alphanumeric custom IDs (e.g. 'INV-2026-001')
String formatDisplayInvoiceNumber(String? raw) {
  if (raw == null || raw.trim().isEmpty) return '';
  String clean = raw.trim();
  if (clean.startsWith('#')) {
    clean = clean.substring(1).trim();
  }
  final intVal = int.tryParse(clean);
  if (intVal != null) {
    // Standard minimal 3-digit padding (e.g. 001, 025, 100)
    return intVal.toString().padLeft(3, '0');
  }
  return clean;
}
