import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:invoiso/common.dart';
import 'package:invoiso/constants.dart';
import 'package:invoiso/models/company_info.dart';
import 'package:invoiso/models/invoice.dart';
import 'pdf_widgets.dart';

pw.MultiPage buildModernTemplate(
  Invoice invoice,
  CompanyInfo? company,
  String currencySymbol,
  String invoicePrefix, {
  String? upiId,
  bool showUpiQr = false,
  bool showGst = true,
  bool showQuantity = true,
  bool showDiscount = true,
  bool showTypeTag = true,
  bool showAliasName = false,
  BusinessType businessType = BusinessType.both,
  BankAccount? bankAccount,
  String datePattern = 'dd/MM/yyyy',
  LogoPosition logoPosition = LogoPosition.left,
  double logoSizePx = 90,
  Uint8List? logoBytes,
  String thankYouNote = '',
  bool showFooterBranding = true,
  PdfColor? themeColor,
  Uint8List? signatureBytes,
  String signaturePosition = 'left',
  double signatureSizePx = 50,
  double previousBalanceDue = 0.0,
  PdfPageFormat pageFormat = PdfPageFormat.a4,
  pw.ThemeData? pdfTheme,
  Uint8List? watermarkBytes,
  double watermarkOpacity = 0.12,
  bool showCgstSgst = false,
  bool showRoundOff = false,
}) {
  final accentColor = themeColor ?? PdfColors.blue600;
  final logoImage = logoBytes != null ? pw.MemoryImage(logoBytes) : null;
  final signatureImage =
      signatureBytes != null ? pw.MemoryImage(signatureBytes) : null;
  final thankyouNote = thankYouNote;

  final title = (invoice.invoiceTitle?.trim().isNotEmpty ?? false)
      ? invoice.invoiceTitle!.toUpperCase()
      : invoice.type.toUpperCase();

  final gstin = company?.gstin ?? '';
  final gstLabel = taxLabel(company?.country);
  final panNumber = company?.panNumber ?? '';
  final fssaiCode = company?.fssaiCode ?? '';
  final companyIdLine = [
    if (showGst && gstin.isNotEmpty) '$gstLabel: $gstin',
    if (panNumber.isNotEmpty) '${panLabel(company?.country)}: $panNumber',
    if (fssaiCode.isNotEmpty) 'FSSAI: $fssaiCode',
  ].join('   ');

  return pw.MultiPage(
    pageFormat: pageFormat,
    theme: pdfTheme,
    margin: const pw.EdgeInsets.all(0),
    footer: (context) => pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 30, vertical: 8),
      alignment: pw.Alignment.centerRight,
      child: pw.Text(
        showFooterBranding
            ? "Page ${context.pageNumber} of ${context.pagesCount}  -  Generated by Yatri Billing"
            : "Page ${context.pageNumber} of ${context.pagesCount}",
        style: pw.TextStyle(fontSize: PdfLayout.footerBrandingFontSize, color: PdfColors.grey600),
      ),
    ),
    build: (context) => [
      pw.Container(
        color: accentColor,
        padding: pw.EdgeInsets.only(
            left: PdfLayout.defaultHMargin,
            right: PdfLayout.defaultHMargin,
            top: PdfLayout.defaultVMargin,
            bottom: PdfLayout.defaultVMargin-5),
        child: pw.Column(
          children: [
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                if (logoImage != null && logoPosition == LogoPosition.left)
                  buildCompanyLogo(logoImage, size: logoSizePx),
                pw.Expanded(
                  flex: 2,
                  fit: pw.FlexFit.loose,
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(company?.name ?? '',
                          style: pw.TextStyle(
                              fontSize: modernPdfStyle.titleFontSize,
                              fontWeight: pw.FontWeight.bold,
                              color: PdfColors.white)),
                      pw.SizedBox(height: modernPdfStyle.headerGap),
                      pw.Text(company?.address ?? '',
                          style: pw.TextStyle(
                              color: PdfColors.white, fontSize: modernPdfStyle.subtitleFontSize)),
                      pw.Text('Phone: ${company?.phone ?? ''}',
                          style: pw.TextStyle(
                              color: PdfColors.white, fontSize: modernPdfStyle.subtitleFontSize)),
                      pw.Text('Email: ${company?.email ?? ''}',
                          style: pw.TextStyle(
                              color: PdfColors.white, fontSize: modernPdfStyle.subtitleFontSize)),
                      if ((company?.website ?? '').isNotEmpty)
                        pw.Text(company!.website,
                            style: pw.TextStyle(
                                color: PdfColors.white, fontSize: modernPdfStyle.subtitleFontSize)),
                    ],
                  ),
                ),
                if (logoImage != null && logoPosition == LogoPosition.right)
                  buildCompanyLogo(logoImage, size: logoSizePx),
              ],
            ),
          ]
        ),
      ),
      if (companyIdLine.isNotEmpty)
      pw.Container(
        color: accentColor,
        padding: pw.EdgeInsets.only(
            left: PdfLayout.defaultHMargin,
            right: PdfLayout.defaultHMargin,
            top: 0,
            bottom: PdfLayout.defaultVMargin-5),
        child: pw.Row(
            mainAxisSize: pw.MainAxisSize.max,
            mainAxisAlignment: pw.MainAxisAlignment.center,
            children: [
                pw.Text(companyIdLine,
                    style: pw.TextStyle(
                        color: PdfColors.white,
                        fontStyle: pw.FontStyle.italic,
                        fontSize: modernPdfStyle.subtitleFontSize)),
            ]
        ),
      ),
      pw.SizedBox(height: 2),
      pw.Center(child: pw.Text(title,
        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: modernPdfStyle.typeFont),),),
      pw.Padding(
        padding: pw.EdgeInsets.fromLTRB(
            PdfLayout.defaultHMargin, 8, PdfLayout.defaultHMargin, 8),
        child: pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Container(
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(6),
              ),
              padding: const pw.EdgeInsets.all(10),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text("BILL TO",
                      style: pw.TextStyle(
                          fontSize: modernPdfStyle.labelFontSize,
                          fontWeight: pw.FontWeight.bold,
                          color: accentColor)),
                  pw.SizedBox(height: 4),
                  pw.Text(invoice.customer.name,
                      style: pw.TextStyle(
                          fontSize: modernPdfStyle.bodyFontSize, fontWeight: pw.FontWeight.bold)),
                  if (invoice.customer.businessName.isNotEmpty)
                    pw.Text(invoice.customer.businessName,
                        style: pw.TextStyle(fontSize: modernPdfStyle.bodyFontSize)),
                  pw.Text(invoice.customer.address,
                      style: pw.TextStyle(fontSize: modernPdfStyle.bodyFontSize)),
                  pw.Text(invoice.customer.phone,
                      style: pw.TextStyle(fontSize: modernPdfStyle.bodyFontSize)),
                  pw.Text(invoice.customer.email,
                      style: pw.TextStyle(fontSize: modernPdfStyle.bodyFontSize)),
                  if (showGst)
                    pw.Text(
                        "${taxLabel(company?.country)}: ${invoice.customer.gstin}",
                        style: pw.TextStyle(
                            fontSize: modernPdfStyle.bodyFontSize, fontStyle: pw.FontStyle.italic)),
                ],
              ),
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text("#: $invoicePrefix${invoice.invoiceNumber ?? invoice.id}",
                    style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold, fontSize: modernPdfStyle.bodyFontSize)),
                pw.Text("Date: ${formatPdfDate(invoice.date, datePattern)}",
                    style: pw.TextStyle(fontSize: modernPdfStyle.bodyFontSize)),
                if (invoice.dueDate != null)
                  pw.Text(
                      "Due Date: ${formatPdfDate(invoice.dueDate!, datePattern)}",
                      style: pw.TextStyle(fontSize: modernPdfStyle.bodyFontSize)),
              ],
            ),
          ],
        ),
      ),

      pw.SizedBox(height: 3),

      pw.Padding(
        padding: pw.EdgeInsets.symmetric(horizontal: PdfLayout.defaultHMargin),
        child: buildInvoiceTable(invoice,
            InvoiceTemplate.modern,
            headerColor: accentColor,
            textColor: PdfColors.white,
            showGst: showGst,
            showQuantity: showQuantity,
            showDiscount: showDiscount,
            showTypeTag: showTypeTag,
            showAliasName: showAliasName,
            businessType: businessType,
            watermarkBytes: watermarkBytes,
            watermarkOpacity: watermarkOpacity,
            tableFontSize: modernPdfStyle.tableFontSize,
            cellPaddingH: modernPdfStyle.cellPaddingH,
            cellPaddingV: modernPdfStyle.cellPaddingV,
            showCgstSgst: showCgstSgst,),
      ),

      pw.SizedBox(height: 5),

      pw.Padding(
        padding: pw.EdgeInsets.symmetric(horizontal: PdfLayout.defaultHMargin),
        child: pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Expanded(child: buildAdditionalNotes(invoice)),
            pw.SizedBox(width: 20),
            buildEnhancedTotals(
              invoice,
              PdfColors.blue200,
              PdfColors.black,
              accentColor,
              currencySymbol,
              previousBalanceDue: previousBalanceDue,
              showCgstSgst: showCgstSgst,
              showRoundOff: showRoundOff,
              fontSize: modernPdfStyle.totalsFontSize
            ),
          ],
        ),
      ),

      if (signatureImage != null) ...[
        pw.SizedBox(height: 16),
        pw.Padding(
          padding: pw.EdgeInsets.symmetric(horizontal: PdfLayout.defaultHMargin),
          child: buildSignatureWidget(signatureImage, signaturePosition,
            imageHeight: signatureSizePx),
        ),
      ],

      if (showUpiQr && upiId != null || bankAccount != null)
        pw.SizedBox(height: 12),

      if (showUpiQr && upiId != null || bankAccount != null)
        pw.Padding(
          padding: pw.EdgeInsets.symmetric(horizontal: PdfLayout.defaultHMargin),
          child: pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                if (showUpiQr && upiId != null)
                  buildUpiQrSection(
                    upiId: upiId,
                    companyName: company?.name ?? '',
                    amount: invoice.total,
                    currencyCode: invoice.currencyCode,
                    invoiceId: invoice.id,
                    accentColor: accentColor,
                  ),
                if (bankAccount != null) ...[
                  if (showUpiQr && upiId != null) pw.SizedBox(height: 12),
                  buildBankDetailsSection(
                      bankAccount: bankAccount, accentColor: accentColor),
                ],
              ],
            ),
          ),
        ),

      pw.Spacer(),

      pw.Container(
        color: accentColor,
        padding: pw.EdgeInsets.all(PdfLayout.defaultHMargin - 12),
        child: pw.Center(
          child: pw.Text(thankyouNote,
              style: pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: PdfLayout.thankYouNoteFontSize,
                  fontWeight: pw.FontWeight.bold)),
        ),
      ),
    ],
  );
}
