import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:invoiso/common.dart';
import 'package:invoiso/constants.dart';
import 'package:invoiso/models/company_info.dart';
import 'package:invoiso/models/invoice.dart';
import 'pdf_widgets.dart';

pw.MultiPage buildCompactTemplate(
  Invoice invoice,
  CompanyInfo? company,
  String currencySymbol,
  String invoicePrefix, {
  String? upiId,
  bool showUpiQr = false,
  bool showGst = true,
  bool showQuantity = true,
  bool showDiscount = true,
  bool showTypeTag = true,
  bool showAliasName = false,
  BusinessType businessType = BusinessType.both,
  BankAccount? bankAccount,
  String datePattern = 'dd/MM/yyyy',
  LogoPosition logoPosition = LogoPosition.left,
  double logoSizePx = 60,
  Uint8List? logoBytes,
  String thankYouNote = '',
  bool showFooterBranding = false,
  PdfColor? themeColor,
  Uint8List? signatureBytes,
  String signaturePosition = 'left',
  double signatureSizePx = 50,
  double previousBalanceDue = 0.0,
  bool showTotalQuantity = false,
  PdfPageFormat pageFormat = PdfPageFormat.a6,
  pw.ThemeData? pdfTheme,
  Uint8List? watermarkBytes,
  double watermarkOpacity = 0.12,
  bool showCgstSgst = false,
  bool showRoundOff = false,
}) {
  final accentColor = themeColor ?? PdfColors.black;
  final logoImage = logoBytes != null ? pw.MemoryImage(logoBytes) : null;
  final signatureImage =
      signatureBytes != null ? pw.MemoryImage(signatureBytes) : null;

  final double fontScale = pageFormat == PdfPageFormat.a6 ? 0.78 : 1.0;
  final double tableFontSize = pageFormat == PdfPageFormat.a6
      ? compactPdfLayoutStyle.tableFontSize
      : 10 * fontScale;
  final double cellPaddingH = pageFormat == PdfPageFormat.a6
      ? compactPdfLayoutStyle.tableHorizontalPadding
      : 6.0;
  final double cellPaddingV = pageFormat == PdfPageFormat.a6
      ? compactPdfLayoutStyle.tableVerticalPadding
      : (8 * fontScale).clamp(4.0, 8.0);
  final double totalsFontSize = compactPdfLayoutStyle.totalsFontSize * fontScale;
  final double headerFont = compactPdfLayoutStyle.titleFontSize * fontScale;
  final double labelFont = compactPdfLayoutStyle.subtitleFontSize * fontScale;
  final double addressFont = compactPdfLayoutStyle.subtitleFontSize * fontScale;
  final double sectionHeaderFont = compactPdfLayoutStyle.subtitleFontSize * fontScale;
  final double bodyFont = compactPdfLayoutStyle.bodyFontSize * fontScale;
  final double pageMargin = pageFormat == PdfPageFormat.a6 ? 16.0 : 20.0;

  final title = (invoice.invoiceTitle?.trim().isNotEmpty ?? false)
      ? invoice.invoiceTitle!.toUpperCase()
      : invoice.type.toUpperCase();

  final totalQty = showTotalQuantity
      ? invoice.items.fold<double>(0, (s, i) => s + i.quantity)
      : 0.0;
  // final qtyLabel = (invoice.quantityLabel?.isNotEmpty == true)
  //     ? invoice.quantityLabel!
  //     : 'Qty';
  final compactLogoSize = pageFormat == PdfPageFormat.a6
      ? logoSizePx * compactPdfLayoutStyle.logoScale
      : logoSizePx;

  final gstin = company?.gstin ?? '';
  final gstLabel = taxLabel(company?.country);
  final panNumber = company?.panNumber ?? '';
  final fssaiCode = company?.fssaiCode ?? '';
  final companyIdLine = [
    if (showGst && gstin.isNotEmpty) '$gstLabel: $gstin',
    if (panNumber.isNotEmpty) '${panLabel(company?.country)}: $panNumber',
    if (fssaiCode.isNotEmpty) 'FSSAI: $fssaiCode',
  ].join('   ');

  return pw.MultiPage(
    pageFormat: pageFormat,
    theme: pdfTheme,
    margin: pw.EdgeInsets.all(pageMargin),
    footer: (context) => pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: pw.EdgeInsets.only(top: compactPdfLayoutStyle.footerTopMargin),
      child: pw.Text(
        showFooterBranding
            ? "Page ${context.pageNumber} of ${context.pagesCount}  -  Generated by Yatri Billing"
            : "Page ${context.pageNumber} of ${context.pagesCount}",
        style: pw.TextStyle(
          fontSize: compactPdfLayoutStyle.footerBrandingFontSize,
          color: PdfColors.grey600,
        ),
      ),
    ),
    build: (context) => [
      // ── Header + invoice details ──
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          if (logoImage != null && logoPosition == LogoPosition.left) ...[
            buildCompanyLogo(logoImage, size: compactLogoSize),
            pw.SizedBox(width: compactPdfLayoutStyle.headerGap),
          ],
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  title,
                  style: pw.TextStyle(
                    fontSize: labelFont,
                    fontWeight: pw.FontWeight.bold,
                    color: accentColor,
                  ),
                ),
                pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Expanded(
                      child: pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text(
                            company?.name ?? '',
                            style: pw.TextStyle(
                                fontSize: headerFont,
                                fontWeight: pw.FontWeight.bold),
                          ),
                          if ((company?.address ?? '').isNotEmpty)
                            pw.Text(company!.address,
                                style: pw.TextStyle(
                                    fontSize: addressFont,
                                    color: PdfColors.grey700)),
                          if ((company?.phone ?? '').isNotEmpty)
                            pw.Text('Phone: ${company!.phone}',
                                style: pw.TextStyle(
                                    fontSize: addressFont,
                                    color: PdfColors.grey700)),
                          if (companyIdLine.isNotEmpty)
                            pw.Text(companyIdLine,
                                style: pw.TextStyle(
                                    fontSize: addressFont,
                                    color: PdfColors.grey700)),
                        ],
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 4),
                pw.Container(
                  decoration: pw.BoxDecoration(
                    border:
                        pw.Border.all(color: PdfColors.grey400, width: 0.5),
                  ),
                  child: pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Expanded(
                        child: pw.Container(
                          padding: pw.EdgeInsets.all(
                              compactPdfLayoutStyle.headerPadding),
                          decoration: const pw.BoxDecoration(
                            border: pw.Border(
                              right: pw.BorderSide(
                                  color: PdfColors.grey400, width: 0.5),
                            ),
                          ),
                          child: pw.Column(
                            crossAxisAlignment: pw.CrossAxisAlignment.start,
                            children: [
                              pw.Text('Bill To:',
                                  style: pw.TextStyle(
                                      fontSize: sectionHeaderFont,
                                      fontWeight: pw.FontWeight.bold)),
                              pw.SizedBox(height: 1),
                              pw.Text(invoice.customer.name,
                                  style: pw.TextStyle(fontSize: bodyFont)),
                              if (invoice.customer.businessName.isNotEmpty)
                                pw.Text(invoice.customer.businessName,
                                    style: pw.TextStyle(
                                        fontSize: addressFont,
                                        color: PdfColors.grey700)),
                              if (invoice.customer.address.isNotEmpty)
                                pw.Text(invoice.customer.address,
                                    style: pw.TextStyle(
                                        fontSize: addressFont,
                                        color: PdfColors.grey700)),
                              if (showGst &&
                                  invoice.customer.gstin.isNotEmpty)
                                pw.Text(
                                    '${taxLabel(company?.country)}: ${invoice.customer.gstin}',
                                    style: pw.TextStyle(
                                        fontSize: addressFont,
                                        color: PdfColors.grey700)),
                            ],
                          ),
                        ),
                      ),
                      pw.Expanded(
                        child: pw.Padding(
                          padding: pw.EdgeInsets.all(
                              compactPdfLayoutStyle.headerPadding),
                          child: pw.Column(
                            crossAxisAlignment: pw.CrossAxisAlignment.start,
                            children: [
                              pw.Text('Invoice Details:',
                                  style: pw.TextStyle(
                                      fontSize: sectionHeaderFont,
                                      fontWeight: pw.FontWeight.bold)),
                              pw.SizedBox(height: 1),
                              pw.Text('No: $invoicePrefix${invoice.invoiceNumber ?? invoice.id}',
                                  style: pw.TextStyle(fontSize: addressFont)),
                              pw.Text(
                                  'Date: ${formatPdfDate(invoice.date, datePattern)}',
                                  style: pw.TextStyle(fontSize: addressFont)),
                              if (invoice.dueDate != null)
                                pw.Text(
                                    'Due: ${formatPdfDate(invoice.dueDate!, datePattern)}',
                                    style:
                                        pw.TextStyle(fontSize: addressFont)),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          if (logoImage != null && logoPosition == LogoPosition.right) ...[
            pw.SizedBox(width: compactPdfLayoutStyle.headerGap),
            buildCompanyLogo(logoImage, size: compactLogoSize),
          ],
        ],
      ),
      pw.SizedBox(height: 6),

      // ── Items Table ──
      buildInvoiceTable(
        invoice,
        InvoiceTemplate.compact,
        headerColor: PdfColors.grey200,
        textColor: PdfColors.black,
        showGst: showGst,
        showQuantity: showQuantity,
        showDiscount: showDiscount,
        showTypeTag: showTypeTag,
        showAliasName: showAliasName,
        businessType: businessType,
        tableFontSize: tableFontSize,
        cellPaddingH: cellPaddingH,
        cellPaddingV: cellPaddingV,
        showCgstSgst: showCgstSgst,
        totalQuantityText: showTotalQuantity && showQuantity
            ? '${totalQty == totalQty.roundToDouble() ? totalQty.toInt() : totalQty}'
            : null,
        watermarkBytes: watermarkBytes,
        watermarkOpacity: watermarkOpacity,
      ),

      pw.SizedBox(height: 6),

      // ── Totals ──
      pw.Align(
        alignment: pw.Alignment.centerRight,
        child: buildEnhancedTotals(
          invoice,
          PdfColors.grey100,
          PdfColors.black,
          accentColor,
          currencySymbol,
          previousBalanceDue: previousBalanceDue,
          fontSize: totalsFontSize,
          compact: true,
          showCgstSgst: showCgstSgst,
          showRoundOff: showRoundOff,
        ),
      ),

      // ── Signature ──
      if (signatureImage != null) ...[
        pw.SizedBox(height: compactPdfLayoutStyle.signatureTopGap),
        buildSignatureWidget(
          signatureImage,
          signaturePosition,
          imageHeight:
              compactPdfLayoutStyle.signatureImageHeight * (signatureSizePx / 50),
          labelGap: compactPdfLayoutStyle.signatureLabelGap,
          labelFontSize: compactPdfLayoutStyle.signatureLabelFontSize,
        ),
      ],

      // ── UPI + Bank (optional) ──
      if ((showUpiQr && upiId != null) || bankAccount != null)
        pw.SizedBox(height: 10),
      if ((showUpiQr && upiId != null) || bankAccount != null)
        pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              if (showUpiQr && upiId != null)
                buildUpiQrSection(
                  upiId: upiId,
                  companyName: company?.name ?? '',
                  amount: invoice.total,
                  currencyCode: invoice.currencyCode,
                  invoiceId: invoice.id,
                  accentColor: accentColor,
                ),
              if (bankAccount != null) ...[
                if (showUpiQr && upiId != null) pw.SizedBox(height: 8),
                buildBankDetailsSection(
                    bankAccount: bankAccount, accentColor: accentColor),
              ],
            ],
          ),
        ),

      if (thankYouNote.isNotEmpty) ...[
        pw.SizedBox(height: 8),
        pw.Center(
          child: pw.Text(thankYouNote,
              style: pw.TextStyle(
                  color: accentColor,
                  fontSize: (PdfLayout.thankYouNoteFontSize - 2) * fontScale,
                  fontWeight: pw.FontWeight.bold)),
        ),
      ],
    ],
  );
}
