# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
script_template: setup_template.iss
app_id: 78E9829EBA0F7AA1FEF92EB60916D9E4
publisher: Yatri Cloud
publisher_url: https://yatricloud.com
display_name: Yatri Billing
create_desktop_icon: true
output_base_filename: InvoiceAppSetup
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
setup_icon_file: assets\exe\images\logo.ico
locales:
  - en